jobs:
- job: BuildMacOS
  pool:
    vmImage: 'macOS-10.15'

  timeoutInMinutes: 360

  steps:
  - script: ci/azure/macos_script
    name: main
    displayName: 'Build and test'
- job: BuildLinux
  pool:
    vmImage: 'ubuntu-18.04'

  timeoutInMinutes: 360

  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/linux_script
    name: main
    displayName: 'Build and test'
- job: BuildWindows
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 360
  steps:
  - powershell: |
      (New-Object Net.WebClient).DownloadFile("https://github.com/msys2/msys2-installer/releases/download/2020-09-03/msys2-base-x86_64-20200903.sfx.exe", "sfx.exe")
      .\sfx.exe -y -o\
      del sfx.exe
    displayName: Download/Extract/Install MSYS2
  - script: |
      @REM install updated filesystem package first without dependency checking
      @REM because of: https://github.com/msys2/MSYS2-packages/issues/2021
      %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Sydd filesystem"
    displayName: Workaround filesystem dash MSYS2 dependency issue
  - script: |
      %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
      %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
    displayName: Update MSYS2
  - script: ci/azure/windows_msvc_build_script.bat
    name: build
    displayName: 'Build'
  - script: ci/azure/windows_msvc_test_script.bat
    name: test
    displayName: 'Test'
